version: '3'
services:
  backend:  
    container_name: backend
    image: jansvoboda596/ml-runner:java-backend
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    networks:
      - frontend
      - runner_agents
  
  frontend:
    container_name: frontend
    image: jansvoboda596/ml-runner:react-frontend
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - frontend

networks:
  frontend:
  runner_agents:
    name: runner_agents
    internal: true