version: '3'
services:
  database:
      container_name: database_local
      image: mysql-database
      build:  
        context: ../database
        dockerfile: Dockerfile
      ports:
        - "3306:3306"  
      environment:
        - MYSQL_ROOT_PASSWORD=mysql
        - MYSQL_DATABASE=machine_learning_database
      volumes:
        - ~/database_test:/var/lib/mysql
      networks:
        - database
      command: 
        mysqld --init-file="/tmp/database/init.sql"   
  
  backend:
    container_name: backend_local
    image: backend
    build:  
      context: ../java
      dockerfile: Dockerfile
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    restart: 
      unless-stopped  
    networks:
      - frontend
      - runner_agents
      - backend
      - database

  frontend:
    container_name: frontend_local
    image: frontend
    build:  
      context: ../react
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - frontend     

  nginx:
    container_name: nginx_local
    image: nginx-reverse-proxy
    build:  
      context: ../nginx
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "80:80"
    networks:
      - frontend
      - backend      
  
networks:
  frontend:
  backend:
  database:
  runner_agents:
    internal: true