version: '3'
services:
  nginx:
    container_name: nginx
    image: jansvoboda596/ml-runner:nginx
    stdin_open: true
    ports:
      - "80:80"
    networks:
      - frontend
      - backend  

  backend:
    container_name: backend
    image: jansvoboda596/ml-runner:java-backend
    environment:
      - JWT_SECRET
      - EMAIL
      - EMAIL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  
    restart: 
      unless-stopped  
    networks:
      - frontend
      - backend
      - database

  frontend:
    container_name: frontend
    image: jansvoboda596/ml-runner:react-frontend
    stdin_open: true
    networks:
      - frontend

  database: 
    container_name: database
    image: mysql
    ports:
      - "3306:3306"  
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ~/database:/var/lib/mysql
    networks:
      - database
  
networks:
  frontend:
  backend:
  database:
 