version: "3"
services:
    db:
      container_name: db-first
      image: mysql
      ports:
       - "3306:3306"  
      environment:
         - MYSQL_ROOT_PASSWORD=mysql
         - MYSQL_DATABASE=machine_learning_database
      volumes:
         - ~/database_test:/var/lib/mysql
      command: mysqld --init-file="/tmp/database/init.sql"