name: Docker Java

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@master
      
    - name: Start Docker engine
      run: sudo systemctl start docker
      
    - name: Build the Docker image
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./java
        push: true
        tags: jansvoboda596/ml-runner:java-backend
