name: React tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: React tests
      uses: actions/setup-node@v2
      with:
        cache: 'npm'
        cache-dependency-path: react/ml-runner/package-lock.json
    - run: |
        cd react/ml-runner
        npm ci
        npm run build --if-present
        npm test
