name: React tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: react-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          cache-dependency-path: react/ml-runner/package-lock.json
      - name: Tests
        env:
          CI: false
        run: |
          cd react/ml-runner
          npm ci
          npm run build --if-present
          npm test
